# Generated by Django 4.2.7 on 2025-02-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewsession_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('coding_round', 'Coding Round'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
