# Generated by Django 4.2.7 on 2025-02-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_alter_interviewsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='final_coding_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
